version: '3.9'
services:
  rabbitmq:
    # Management image because development environment
    # Using slightly older rabbitmq image becasue persmission issue
    # ref: https://github.com/mpast/mobileAudit/issues/44#issuecomment-932316685
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Asia/Dhaka
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./.docker/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./product_aggregator/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  sitemap_scraper:
    build: ./sitemap_scraper/
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
    environment:
      - RABBITHOST=rabbitmq
  product_scraper:
    build: ./product_scraper/
    depends_on:
    - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
    environment:
      - RABBITHOST=rabbitmq
  product_aggregator:
    build: ./product_aggregator/
    depends_on:
    - rabbitmq
    - postgres
    links:
      - "rabbitmq:rabbitmq"
      - "postgres:postgres"
    environment:
      - RABBITHOST=rabbitmq
      - PGHOST=postgres
    